services:
  webapp:
    image: giangnnt260703/kfs_api:latest
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      TZ: "Asia/Ho_Chi_Minh"
    depends_on:
      - sqlserver
      - cache
    networks:
      - webnet

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "giangpro123@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Evaluation"
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - sql_data:/var/opt/mssql
      - /etc/sqlbak:/etc/sqlbak
    restart: on-failure
    networks:
      - webnet

  cache:
    image: redis
    environment:
      - REDIS_PASSWORD=giangpro123@
    ports:
      - 6379:6379
    restart: always
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  sql_data: